selector-name: "&aQuick Connect"
selector-gui-title: "&7AnimeWorld Servers: Page 1"
us-servers-name: "&a&lUS Servers &7&o(Right-click)"
fr-servers-name: "&b&lFR Servers &7&o(Right-click)"

# This is an example on how to setup the servers
# so that they show in the selector.
servers:
  US-1: # This will be displayed in the item selector as the name of the server/world.
    location: "US" # This is so we know wether or not the server is US/FR.
    bungee-redirect: "mini-1" # This is the actual Bungee location of the server.
  FR-1:
    location: "FR"
    bungee-redirect: "mini-2"

lobbies:
  Lobby-1:
    bungee-redirect: "mini-3"